<?php
/** Charcoal photography footer. @package MNYphoto */
defined( 'ABSPATH' ) || exit;
?>
<footer class="site-footer" id="site-footer"><div class="shell footer-top"><div><?php get_template_part( 'template-parts/page-shared/content', 'shared-brand' ); ?><p><?php esc_html_e( 'Your world, in focus.', 'mnyphoto-theme' ); ?><br><?php esc_html_e( 'People, pets, places & everything that matters.', 'mnyphoto-theme' ); ?></p></div>
<nav aria-label="<?php esc_attr_e( 'Footer pages', 'mnyphoto-theme' ); ?>"><span class="eyebrow"><?php esc_html_e( 'EXPLORE', 'mnyphoto-theme' ); ?></span><?php if ( has_nav_menu( 'footer' ) ) { wp_nav_menu( array( 'theme_location' => 'footer', 'container' => false, 'menu_class' => 'footer-links', 'depth' => 1 ) ); } else { foreach ( array( 'services' => __( 'Services', 'mnyphoto-theme' ), 'about' => __( 'About', 'mnyphoto-theme' ), 'portfolio' => __( 'Portfolio', 'mnyphoto-theme' ), 'blog' => __( 'Blog', 'mnyphoto-theme' ) ) as $key => $label ) { ?><a href="<?php echo esc_url( mnyphoto_url( $key ) ); ?>"><?php echo esc_html( $label ); ?></a><?php } } ?></nav>
<nav aria-label="<?php esc_attr_e( 'Photography categories', 'mnyphoto-theme' ); ?>"><span class="eyebrow"><?php esc_html_e( 'IN THE FRAME', 'mnyphoto-theme' ); ?></span><?php foreach ( mnyphoto_categories() as $category ) : ?><a href="<?php echo esc_url( mnyphoto_url( 'services' ) . '#service-' . $category['id'] ); ?>"><?php echo esc_html( $category['name'] ); ?></a><?php endforeach; ?></nav>
<nav aria-label="<?php esc_attr_e( 'Footer contact', 'mnyphoto-theme' ); ?>"><span class="eyebrow"><?php esc_html_e( 'SAY HELLO', 'mnyphoto-theme' ); ?></span><a href="<?php echo esc_url( mnyphoto_url( 'contact' ) ); ?>"><?php esc_html_e( 'Contact Us', 'mnyphoto-theme' ); ?> ↗</a><?php if ( get_privacy_policy_url() ) : ?><a href="<?php echo esc_url( get_privacy_policy_url() ); ?>"><?php esc_html_e( 'Privacy Policy', 'mnyphoto-theme' ); ?></a><?php endif; ?><a href="<?php echo esc_url( mnyphoto_url( 'search' ) ); ?>"><?php esc_html_e( 'Search the site', 'mnyphoto-theme' ); ?></a></nav></div>
<div class="shell footer-bottom"><span>© <?php echo esc_html( gmdate( 'Y' ) ); ?> MNY Photo</span><?php if ( mnyphoto_has_examples() ) : ?><span><?php esc_html_e( 'Includes AI-generated illustrative photography', 'mnyphoto-theme' ); ?></span><?php endif; ?><a href="#content"><?php esc_html_e( 'Back to the top', 'mnyphoto-theme' ); ?> ↑</a></div></footer>
