<?php
/** Photography presentation. @package MNYphoto */
defined( 'ABSPATH' ) || exit;
?>
<?php
$status = isset( $_GET['brief'] ) && is_string( $_GET['brief'] ) ? sanitize_key( wp_unslash( $_GET['brief'] ) ) : '';
$selected_category = isset( $_GET['category'] ) && is_string( $_GET['category'] ) ? sanitize_key( wp_unslash( $_GET['category'] ) ) : '';
?>
<form id="project-brief" method="post" action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>" aria-label="<?php esc_attr_e( 'Photography inquiry', 'mnyphoto-theme' ); ?>">
<input type="hidden" name="action" value="nytt99_project_brief"><?php wp_nonce_field( 'nytt99_project_brief', 'nytt99_project_brief_nonce' ); ?>
<label class="form-honeypot" aria-hidden="true"><?php esc_html_e( 'Website', 'mnyphoto-theme' ); ?><input name="project_website" tabindex="-1" autocomplete="off"></label>
<?php if ( in_array( $status, array( 'sent', 'invalid', 'error' ), true ) ) : ?><p class="form-message" role="<?php echo 'sent' === $status ? 'status' : 'alert'; ?>" tabindex="-1" data-form-notice><?php if ( 'sent' === $status ) { esc_html_e( 'Thank you. Your photography inquiry has been sent.', 'mnyphoto-theme' ); } elseif ( 'invalid' === $status ) { esc_html_e( 'Please provide your name, a valid email, a photography category, and a message. Check your preferred date if supplied.', 'mnyphoto-theme' ); } else { esc_html_e( 'Your inquiry could not be sent. Please try again later or use the email link.', 'mnyphoto-theme' ); } ?></p><?php endif; ?>
<div class="form-grid"><label><?php esc_html_e( 'Your name', 'mnyphoto-theme' ); ?><input name="project_name" autocomplete="name" required maxlength="150" placeholder="<?php esc_attr_e( 'First and last name', 'mnyphoto-theme' ); ?>"></label><label><?php esc_html_e( 'Email address', 'mnyphoto-theme' ); ?><input type="email" name="project_email" autocomplete="email" required maxlength="254" placeholder="you@example.com"></label><label class="full"><?php esc_html_e( 'What are we photographing?', 'mnyphoto-theme' ); ?><select name="project_area[]" required><option value=""><?php esc_html_e( 'Choose a photography category', 'mnyphoto-theme' ); ?></option><?php foreach ( mnyphoto_categories() as $category ) : ?><option value="<?php echo esc_attr( $category['id'] ); ?>" <?php selected( $selected_category, $category['id'] ); ?>><?php echo esc_html( $category['name'] ); ?></option><?php endforeach; ?></select></label><label><?php esc_html_e( 'Preferred date', 'mnyphoto-theme' ); ?><input type="date" name="project_timing"></label><label><?php esc_html_e( 'Location', 'mnyphoto-theme' ); ?><input name="project_location" maxlength="250" placeholder="<?php esc_attr_e( 'A place you have in mind', 'mnyphoto-theme' ); ?>"></label><label class="full"><?php esc_html_e( 'Tell us a little about it', 'mnyphoto-theme' ); ?><textarea name="project_context" required maxlength="5000" placeholder="<?php esc_attr_e( 'Who, what, where — and what would make these photographs special to you?', 'mnyphoto-theme' ); ?>"></textarea></label></div>
<p class="small-note"><?php esc_html_e( 'Your inquiry is emailed to the site administrator so we can respond. This theme does not store a copy in the site database.', 'mnyphoto-theme' ); ?> <?php if ( get_privacy_policy_url() ) : ?><a href="<?php echo esc_url( get_privacy_policy_url() ); ?>"><?php esc_html_e( 'Privacy Policy', 'mnyphoto-theme' ); ?></a><?php endif; ?></p><button class="button" type="submit"><?php esc_html_e( 'Send inquiry', 'mnyphoto-theme' ); ?> <span aria-hidden="true">↗</span></button>
</form>